GET http://localhost:5000/todos

###

POST http://localhost:5000/todo/new
Content-Type: application/json

{
    "text":"lovely day 5"
}


###

DELETE http://localhost:5000/todo/delete/64d860243cb571193aeb0c01


###

PUT http://localhost:5000/todo/complete/64d860b29ee4181928345be8